version: '3.1'

services:
  db:
    image: postgres
    ports:
         - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpwd
    volumes:
        - ./data/dumb.sql:/docker-entrypoint-initdb.d/dumb.sql


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080