version: '3.1'

services:
  db:
    image: postgres
    ports:
         - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpwd
    volumes:
        - ./data/initdb.sql:/docker-entrypoint-initdb.d/1-init-database.sql
        - ./data/testdb.sql:/docker-entrypoint-initdb.d/2-init-database.sql


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080